"""
Django settings for pztop project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8a&qrxccy7k-cep_=*^dyl0va^7zcuppw-@$wz=pdx9b+@&334'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'yy',
    'xadmin',
    'crispy_forms',
]
#中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pztop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')], #这里要修改
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pztop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE':'django.db.backends.mysql',
        'NAME':'YY',
        'USER':'root',
        'PASSWORD':'hl951103',
        'HOST': '111.229.129.126',       # 47.97.200.189,
        'PORT':'3306',
        'TEST':{
            'CHARSET':'utf8',
            'COLLATION':'utf8_general_ci'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 把语言改为中文   针对admin页面
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'
# 把国际时区改为中国时区
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = '/data/wwwroot/pz/static'
STATIC_URL = '/static/'  #静态文件别名
#静态文件地址拼接，后面'static'文件为自己建立的存放静态文件（JS，IMG，CSS）的文件名
STATIC_DIRS = [
    os.path.join(BASE_DIR, 'yy/static'),#主文件下静态文件
    os.path.join(BASE_DIR,'yy','static'),#项目yy文件下静态文件
]

# #设置文件上传路径，图片上传、文件上传都会存放在此目录里
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '/media/')

#设置打印日志到屏幕
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'DEBUG',
        },
    }
}

# Django默认支持Session，并且默认是将Session数据存储在数据库中，即：django_session 表中。
# 配置 settings.py
#  SESSION_ENGINE = 'django.contrib.sessions.backends.db' # 引擎（默认）
#  SESSION_COOKIE_NAME ＝ "sessionid"   # Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串（默认）
#  SESSION_COOKIE_PATH ＝ "/"    # Session的cookie保存的路径（默认）
SESSION_COOKIE_DOMAIN = None    # Session的cookie保存的域名（默认）
SESSION_COOKIE_SECURE = False    # 是否Https传输cookie（默认）
SESSION_COOKIE_HTTPONLY = True    # 是否Session的cookie只支持http传输（默认）
SESSION_COOKIE_AGE = 30000    # Session的cookie失效日期（2周）（默认）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # 是否关闭浏览器使得Session过期（默认）
SESSION_SAVE_EVERY_REQUEST = False   # 是否每次请求都保存Session，默认修改之后才保存（默认）


# 也可以自定义配置 但是自定义的配置都要写到配置文件最后 代码中使用时可以导入配置
#
# from django.conf import settings
# settings.配置名

# 配置文件上传目录
#
# #设置文件上传路径
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# 如果想在浏览器里访问自己上传的文件则需要在urls.py做如下设置：
#
# from django.views.static import serve
# from django.conf import settings
#
# urlpatterns = [
#     ...
#     re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
# ]

# AUTH_USER_MODEL = 'yy.UserAdmin'

#加密方式
PASSWORD_HASHERS = (
    # 'yy.hashers.MyMD5PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
)
# AUTHENTICATION_BACKENDS = (
#     'yy.Mybackend.MyBackend',
# )  #用自定义的加密规则


#邮件发送
EMAIL_USE_SSL = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  #发送邮件的后端模块
EMAIL_HOST = 'smtp.qq.com'#发送方的smtp服务器地址，建议使用新浪家的
EMAIL_PORT = 465 #smtp服务端口，qq邮箱默认为465
EMAIL_HOST_USER = '939557447@qq.com' #发送服务器的用户名；
EMAIL_HOST_PASSWORD = '559951103' #对应用户的密码
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
CONFIRM_DAYS = 7